"""
Django settings for rating_site project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from rating_site.env_loader import (
    secret_key,
    api_base_url,
    db_hostname,
    db_username,
    db_password,
    db_port,
    db_name,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key
API_BASE_URL = api_base_url

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'rating.CustomUser'
AUTHENTICATION_BACKENDS = [
    'rating_site.rating.backends.CustomAuthBackend',
]

LOGIN_REDIRECT_URL = '/'

LOGIN_URL = '/accounts/login/'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rating_site.rating.apps.RatingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rating_site.rating_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rating_site.rating.context_processors.frontend_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'rating_site.rating_site.wsgi.application'

# Database ТОЛЬКО ДЛЯ ЛОКАЛЬНОЙ БД
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'mysql_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': f'{db_name}',
        'USER': f'{db_username}',
        'PASSWORD': f'{db_password}',
        'HOST': f'{db_hostname}',
        'PORT': f'{db_port}',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'  # Изменено на русский

TIME_ZONE = 'Europe/Moscow'  # Изменен часовой пояс

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'  # Добавлен слеш в начале
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (загруженные файлы)
MEDIA_URL = '/data/'
MEDIA_ROOT = BASE_DIR.parent / 'data'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'